"""empty message

Revision ID: 03849d64b3dc
Revises: 6b258c44d593
Create Date: 2020-05-10 16:12:52.286054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03849d64b3dc'
down_revision = '6b258c44d593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
