"""empty message

Revision ID: 2518c9924348
Revises: 07cd80421bee
Create Date: 2020-05-12 05:12:07.909223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2518c9924348'
down_revision = '07cd80421bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
