"""empty message

Revision ID: 377fe86da997
Revises: f76bbc4581de
Create Date: 2020-05-11 22:59:34.514746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377fe86da997'
down_revision = 'f76bbc4581de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('venues', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['Venue.city'], ),
    sa.ForeignKeyConstraint(['state'], ['Venue.state'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Area')
    # ### end Alembic commands ###
