"""empty message

Revision ID: 9846c12d8d46
Revises: 03849d64b3dc
Create Date: 2020-05-10 16:14:07.328657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9846c12d8d46'
down_revision = '03849d64b3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(), nullable=True))
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
